# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
timezone: Europe/Warsaw
port: 2038

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - LICENSE
  - README.md
  - "*.code-workspace"
  - package-lock.json
  - package.json
